name: ConanTableCraft

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Install MarkDig
        run: dotnet add package Markdig --version 0.38.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish .NET Project
        run: dotnet publish ConanTableCraft.csproj -c Release -o release --nologo
      - name: Update base-tag in index.html
        run: sed -i 's|<base href="/"/>|<base href="/ConanTableCraft/"/>|g' release/wwwroot/index.html
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
